package com.orastays.propertylist.helper;

public enum PriceType {

	ZERO,
	ROOM_PRICE_PER_NIGHT,
	ROOM_PRICE_PER_MONTH,
	SHARED_BED_PRICE_PER_NIGHT,
	SHARED_BED_PRICE_PER_MONTH,
	COT_PRICE,
	SHARED_COT_PRICE,
	COMMISSION
}
